### ISSUE TITLE
Flash File Invalid when it is a swf file

### ISSUE THREAD

**Issue by primetime43** [zmcj21/OpenSWF2EXE#2]
![image](https://user-images.githubusercontent.com/12754111/206942729-c48a9dfa-dcde-4eca-94ca-17a3495375c4.png)

I selected the swf flash file and the flash player, all done correctly, getting this error. I looked in the code, it seems to be something with this stuff here:
![image](https://user-images.githubusercontent.com/12754111/206942808-8b66f8d5-670c-4b72-b4ce-0d4baa1dbd32.png)

**Comment by zmcj21** [comment]
Hi there. If you have a good solution, please submit a PullRequest.

**Comment by primetime43** [comment]
@zmcj21 could you accept the merge request to fix the issue. Thanks.

**Comment by zmcj21** [comment]
Thank you very much for solving this problem, I will add you to the contributors.
